### ISSUE TITLE
name

### ISSUE THREAD

**Issue by benfoxall** [whiteoctober/bauble#1]
@carlwood came up with the name "bauble".  I like it, though it might be a bit tied to christmas.

Anyone else have any other ideas?

**Comment by carlwood** [comment]
I think this is great

**Comment by benfoxall** [comment]
@carlwood shouldn't be allowed on github

**Comment by dubaussi** [comment]
I like 'axis' as it deals with the x and y coordinates...plus has spin off potential 'axis of evil' 'axis of fun'

**Comment by dubaussi** [comment]
tract/expanse/absorb...actually I'm just drifiting into Zoolander pose names here....'Magnum'

**Comment by benfoxall** [comment]
I like the idea of axis,  I guess you've got words like 'point', 'locate' as well.

MAGNUM

**Comment by Drarok** [comment]
How about _Orb_?

**Comment by benfoxall** [comment]
bauble has grown on me - let's stick to that!
